services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: pnpm run start:dev reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - '3000:3000'
    develop:
      watch:
        - action: sync
          path: ./apps/reservations
          target: /usr/src/app/apps/reservations
          ignore:
            - node_modules/
        - action: rebuild
          path: ./apps/reservations/package.json

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    develop:
      watch:
        - action: sync
          path: ./apps/auth
          target: /usr/src/app/apps/auth
          ignore:
            - node_modules/
        - action: rebuild
          path: ./apps/auth/package.json

  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: pnpm run start:dev payments
    env_file:
      - ./apps/payments/.env
    develop:
      watch:
        - action: sync
          path: ./apps/payments
          target: /usr/src/app/apps/payments
          ignore:
            - node_modules/
        - action: rebuild
          path: ./apps/payments/package.json

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: pnpm run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    develop:
      watch:
        - action: sync
          path: ./apps/notifications
          target: /usr/src/app/apps/notifications
          ignore:
            - node_modules/
        - action: rebuild
          path: ./apps/notifications/package.json

  mongo:
    image: mongo
    ports:
      - '28017:27017'
